application: me-aws
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /tasks/.*
  script: meTasks.py
  login: admin

- url: /starter/.*
  script: meAWS.py
  login: admin

- url: /config/.*
  script: meConfig.py
  login: admin