application: me-finance
version: 1
runtime: python
api_version: 1

skip_files:
- (loaders/.*)
- (simulation/.*)

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /config/.*
  script: meFinance.py
  login: admin

- url: /cron/.*
  script: statPutCron.py
  login: admin

- url: /test/.*
  script: test.py
  login: admin

- url: /test2/.*
  script: test2.py
  login: admin

- url: /convert/delDesires
  script: deleteDesires.py
  login: admin

- url: /convert/doDeltas
  script: doDeltas.py
  login: admin

- url: /convert/.*
  script: meConverter.py
  login: admin

- url: /algorithms/go
  script: meAlgorithm.py
  login: admin

- url: /algorithms/.*
  script: makeAlgorithms.py
  login: admin
