application: me-finance
version: 1
runtime: python
api_version: 1

handlers:
- url: /config/.*
  script: meFinance.py
  login: admin

- url: /cron/.*
  script: statPutCron.py
  login: admin

- url: /test/.*
  script: test.py
  login: admin

- url: /convert/.*
  script: meConverter.py
  login: admin
