application: me-finance
version: 1
runtime: python
api_version: 1

skip_files:
- (loaders/.*)
- (simulation/.*)

builtins:
- datastore_admin: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

#- url: /stats.*
#  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /stats/.*
  script: outputStats.py
  login: admin

- url: /metaAlg/.*
  script: metaAlg.py
  login: admin

- url: /backtest/.*
  script: doBackTests.py
  login: admin

- url: /desire/.*
  script: desireFunc.py
  login: admin

- url: /algorithms/go
  script: meAlgorithm.py
  login: admin

- url: /algorithms/.*
  script: makeAlgorithms.py
  login: admin

- url: /config/.*
  script: meFinance.py
  login: admin

- url: /cron/.*
  script: statPutCron.py
  login: admin

- url: /convert/delDesires
  script: deleteDesires.py
  login: admin

- url: /convert/doDeltas
  script: doDeltas.py
  login: admin

- url: /convert/.*
  script: meConverter.py
  login: admin

- url: /calculate/ntersect
  script: calculateNtersects.py
  login: admin

- url: /calculate/compounds/.*
  script: calculateCompoundReturns.py
  login: admin
