application: me-finance
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /config/.*
  script: meFinance.py
  login: admin

- url: /cron/.*
  script: statPutCron.py
  login: admin

- url: /test/.*
  script: test.py
  login: admin

- url: /convert/doDeltas
  script: doDeltas.py
  login: admin

- url: /convert/.*
  script: meConverter.py
  login: admin

- url: /algorithms/go
  script: meAlgorithm.py
  login: admin

- url: /algorithms/.*
  script: makeAlgorithms.py
  login: admin
